# This is a placeholder so actions won't default to a getting started page

name: Test AWS Openid connection

on: push
env:
  BUCKET_NAME : "githubopenidbucket"
  AWS_REGION : "ap-southeast-2"
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!

  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::435806136393:role/provider-github-openid
          role-session-name: samplerolesession
          aws-region: ${{ env.AWS_REGION }}

      - name: Create bucket in S3
        uses: aitorres/aws-s3-create-bucket@v1.2.0
        with:
          bucket-name: ${{ env.BUCKET_NAME }}
          acl: 'private'

      # archive repo files    
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        
      # Upload a file to AWS s3
      - name:  Copy zip file to s3
        run: |
          aws s3 cp release.zip s3://${{ env.BUCKET_NAME }}/
